remote_theme: "mmistakes/so-simple-theme@3.2.0"
locale: en-US
title: "S2 Blog"
description: "Personal blog about RE and CTF Writeups"
url: ""
baseurl: ""
date_format: "%d-%m-%Y"
skin: "/assets/css/skins/dark.css"
author: sisoma2
google_analytics: UA-2662161-4
markdown: kramdown

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
    
footer_links:
  - title: Twitter
    url: https://twitter.com/sisoma2
    icon: fab fa-twitter
  - title: GitHub
    url: https://github.com/sisoma2
    icon: fab fa-github
  - title: Telegram
    url: https://t.me/sisoma2
    icon: fab fa-telegram
    
plugins:
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 10
paginate_path: /page:num/

liquid:
  error_mode: strict

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: false