remote_theme: "mmistakes/so-simple-theme@3.2.0"
locale: en-US
title: "S2 Blog"
description: "Personal blog about RE and CTF Writeups"
url: "https://s2blog.es"
date_format: "%d-%m-%Y"
skin: "/assets/css/skins/dark.css"

google_analytics: UA-2662161-4

disqus:
  shortname: sisoma2
  
footer_links:
  - title: Twitter
    url: https://twitter.com/sisoma2
    icon: fab fa-twitter-square
  - title: GitHub
    url: https://github.com/sisoma2
    icon: fab fa-github-square
  - title: Telegram
    url: https://t.me/sisoma2
    icon: fab fa-telegram